defaults:
  - _self_
  - metadata/training@_here_
  - designer: diffusion
  - scenario: rware_16_50_5_4_corners

experiment_name: corners_diffusion
n_iters: 5_000
n_epochs: 10
memory_management: gpu
minibatch_size: 1000
n_mini_batches: 10

logging:
  type: wandb
  # wandb_mode: disabled
  wandb_mode: online
  # wandb_mode: offline