defaults:
  - _self_
  - shared/training@_here_

designer: random
experiment_name: env_generalise_bad_shelf
n_iters: 3_000
n_epochs: 5
minibatch_size: 1000
n_mini_batches: 10
scenario:
  size: 16
  n_shelves: 50
  agent_idxs:
  - 1
  - 88
  - 132
  - 233
  - 162
  goal_idxs:
  - 39_
  - 185
  - 237
  - 238
  - 159

logging:
  type: wandb
  # wandb_mode: disabled
  wandb_mode: online